min_version = "2025.1.14"

[tools]
node = "22.12.0"
"npm:lefthook" = "1.8.5"
"npm:@commitlint/config-conventional" = "19.6.0"
"npm:@commitlint/cli" = "19.6.0"
"npm:@commitlint/types" = "19.5.0"
"npm:remark-cli" = "12.0.1"
"npm:remark-validate-links" = "8.0.0"
"npm:remark-lint-no-dead-urls" = "1.1.0"

[tasks."fmt"]
run = ""

[tasks."lint"]
run = ""

[tasks."test"]
run = ""

[tasks."remark"]
run = """
#!/usr/bin/env bash
set -euo pipefail
REMARK_VALIDATE_LINKS="$(mise where npm:remark-validate-links)/lib/node_modules/remark-validate-links/index.js"
REMARK_LINT_NO_DEAD_URLS="$(mise where npm:remark-lint-no-dead-urls)/lib/node_modules/remark-lint-no-dead-urls/index.js"
remark --ignore-path .gitignore --ignore-pattern CHANGELOG.md --quiet --frail --no-stdout --use "$REMARK_VALIDATE_LINKS" --use "$REMARK_LINT_NO_DEAD_URLS" "$@"
"""
